import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'getting-started/what-is-stacktest',
        'getting-started/installation',
        'getting-started/quick-start',
        'getting-started/project-layout',
      ],
    },
    {
      type: 'category',
      label: 'Core Concepts',
      items: [
        'core-concepts/overview',
        'core-concepts/test-projects',
        'core-concepts/test-runs',
        'core-concepts/providers',
        'core-concepts/regions',
        'core-concepts/parameters',
        'core-concepts/artifacts',
        'core-concepts/reports',
        'core-concepts/cleanup-destroy',
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      items: [
        'configuration/overview',
        'configuration/project',
        'configuration/tests',
        'configuration/providers',
        'configuration/parameters-overrides',
        'configuration/dynamic-values',
        'configuration/env-vars',
        'configuration/secrets-handling',
      ],
    },
    {
      type: 'category',
      label: 'CLI Reference',
      items: [
        'cli/reference',
      ],
    },
    {
      type: 'category',
      label: 'Examples & Recipes',
      items: [
        'examples/index',
        'recipes/validate-cfn',
        'recipes/multi-region',
        'recipes/parameter-overrides',
        'recipes/html-report',
        'recipes/clean-failed-runs',
        'recipes/ci-cd',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'architecture/system-overview',
        'architecture/package-structure',
        'architecture/provider-plugin-model',
        'architecture/test-lifecycle',
        'architecture/error-handling',
        'architecture/logging-telemetry',
        'architecture/security-model',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api',
        },
      ],
    },
    {
      type: 'category',
      label: 'Schema Reference',
      items: [
        'schema/stacktest-yml',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      items: [
        'contributing/dev-setup',
        'contributing/coding-standards',
        'contributing/pr-rules',
        'contributing/documentation-rules',
      ],
    },
    {
      type: 'category',
      label: 'AI-Friendly Resources',
      items: [
        'ai/agent-guide',
        'ai/source-of-truth',
      ],
    },
    'troubleshooting',
    'release-notes/changelog',
  ],
};

export default sidebars;
